### Create Bank
POST http://localhost:8080/api/v1/banks
Content-Type: application/json

{
  "name": "Safwa Bank"
}

### Get banks
GET http://localhost:8080/api/v1/banks/1/accounts

### Transfer
POST http://localhost:8080/api/v1/banks/1/accounts/1111/transfer
Content-Type: application/json
Idempotency-Key: transfer-1111-1100-005

{
  "destinationBankId": 1,
  "destinationAccountNumber": "1100",
  "amount": 2000
}

### Create account
POST http://localhost:8080/api/v1/banks/1/accounts
Content-Type: application/json

{
  "ownerName": "Abdel-Rahman",
  "accountNumber": "1100",
  "accountType": "CURRENT"
}

### Delete bank
DELETE http://localhost:8080/api/v1/banks/3

### Delete account
DELETE http://localhost:8080/api/v1/banks/1/accounts/777001

### Deposit
POST http://localhost:8080/api/v1/banks/1/accounts/0011/deposit
Content-Type: application/json
Idempotency-Key: deposit-1111-004

{
  "amount" : 1000000.00
}

### Withdraw
POST http://localhost:8080/api/v1/banks/1/accounts/0011/withdraw
Content-Type: application/json
Idempotency-Key: withdraw-0011-002

{
  "amount": 30000.00
}

### Deposit
POST http://localhost:8080/api/v1/banks/1/accounts/1111/deposit
Content-Type: application/json
Idempotency-Key: deposit-1111-005

{
  "amount": 100
}

