### Create Bank
POST http://localhost:8080/api/v1/banks
Content-Type: application/json

{
  "name": "Safwa Bank"
}

### Get banks
GET http://localhost:8080/api/v1/banks

### Create account
POST http://localhost:8080/api/v1/banks/1/accounts
Content-Type: application/json

{
  "ownerName": "Abdel-Rahman",
  "accountNumber": "1100",
  "accountType": "CURRENT"
}

### Delete bank
DELETE http://localhost:8080/api/v1/banks/3

### Delete account
DELETE http://localhost:8080/api/v1/banks/1/accounts/777001

### Deposit
POST http://localhost:8080/api/v1/banks/1/accounts/0011/deposit
Content-Type: application/json

{
  "amount" : 1000000.00
}

### Withdraw
POST http://localhost:8080/api/v1/banks/1/accounts/0011/withdraw
Content-Type: application/json

{
  "amount": 300000.00
}

