apiVersion: v1
kind: Secret
metadata:
  name: bank-secret
type: Opaque
stringData:
  DB_USERNAME: sanad
  DB_PASSWORD: progressoft
  ARTEMIS_USER: sanad
  ARTEMIS_PASSWORD: "1234"
  JWT_SECRET: "sanadherzalla12345678910111213141516"